[project]
name = "prompt-dom"
version = "0.1.0"
description = "A library for building and rendering nested prompts."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.10.3",
]
